// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoApis.Data;

#nullable disable

namespace TaskApis.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20240623155009_CreateTodo")]
    partial class CreateTodo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("TodoApis.Models.Todo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("Id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("Description");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("DATETIME")
                        .HasColumnName("EndDateTime");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.ToTable("Todos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ebaadb4a-cfe3-4aee-b4e1-228bb094ba5a"),
                            Description = "Buy gorceries",
                            EndDateTime = new DateTime(2024, 6, 28, 15, 50, 9, 336, DateTimeKind.Utc).AddTicks(8160),
                            Title = "Groceries"
                        },
                        new
                        {
                            Id = new Guid("f3926733-b84e-42b5-98d2-7880f525041e"),
                            Description = "Take a form",
                            EndDateTime = new DateTime(2024, 6, 25, 15, 50, 9, 336, DateTimeKind.Utc).AddTicks(8190),
                            Title = "Form"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
